theme: jekyll-theme-midnight
name: BrikMentionのコードサーバー
title: BrikMentionのコードサーバー
url: https://brikmention.github.io/BrikMention-CodeStorage/
liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false
